"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Row=Record<string,unknown>;
const queries=[
 {id:"coverage",title:"Universe coverage",question:"How broad is our coverage across the six universes?",description:"Compare pathway volume, outcomes and maturity.",handling:"Universe ← Stream → CareerOutcome"},
 {id:"domains",title:"Largest domains",question:"Where is pathway knowledge concentrated?",description:"Review the deepest populated career domains.",handling:"Domain ← Stream → CareerOutcome"},
 {id:"governance",title:"Governance maturity",question:"What is published, validated or awaiting review?",description:"Separate ontology maturity from loaded data maturity.",handling:"Universe → governance and version metadata"},
 {id:"exams",title:"Entrance exams",question:"Which examination gateways are represented?",description:"Inspect levels, bodies and universe associations.",handling:"EntranceExam → Universe"},
 {id:"provenance",title:"Source traceability",question:"Can graph knowledge be traced to workbook evidence?",description:"Measure source records and evidence links.",handling:"Entity → SourceRecord"},
 {id:"validation",title:"Structural health",question:"Is the graph structurally ready for review?",description:"Check missing domains, outcomes and dangling careers.",handling:"Stream → Domain and CareerOutcome"},
 {id:"engineering",title:"Engineering example",question:"Which engineering pathways can an aspirant explore?",description:"Run a concrete Question Bank-style discovery query.",handling:"Engineering Domain ← Stream → CareerOutcome"},
];

export default function Home(){
 const[metrics,setMetrics]=useState<Row|null>(null),[active,setActive]=useState(queries[0]),[rows,setRows]=useState<Row[]>([]),[columns,setColumns]=useState<string[]>([]),[status,setStatus]=useState("Connecting to the knowledge graph…"),[busy,setBusy]=useState(false),[term,setTerm]=useState("");
 useEffect(()=>{void initialize();},[]);
 async function request(id:string,term=""){const response=await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,term})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Query failed");return data as{columns:string[];rows:Row[]};}
 async function initialize(){try{const overview=await request("overview");setMetrics(overview.rows[0]||{});setStatus("Live graph connected");await run(queries[0]);}catch(error){setStatus(error instanceof Error?error.message:"Connection failed");}}
 async function run(query:typeof queries[number]){setBusy(true);setActive(query);setStatus(`Running ${query.title}…`);try{const data=await request(query.id);setRows(data.rows);setColumns(data.columns);setStatus(`${data.rows.length} result${data.rows.length===1?"":"s"}`);}catch(error){setStatus(error instanceof Error?error.message:"Query failed");}finally{setBusy(false);}}
 async function search(event:FormEvent){event.preventDefault();if(!term.trim())return;setBusy(true);setActive({id:"search",title:"Career search",question:`What matches “${term.trim()}”?`,description:"Search careers, pathways and domains.",handling:"Domain ← Stream → CareerOutcome"});try{const data=await request("search",term.trim());setRows(data.rows);setColumns(data.columns);setStatus(`${data.rows.length} matches`);}catch(error){setStatus(error instanceof Error?error.message:"Search failed");}finally{setBusy(false);}}
 const cards=useMemo(()=>[["Streams",metrics?.streams],["Career outcomes",metrics?.careers],["Domains",metrics?.domains],["Entrance exams",metrics?.exams],["Skills",metrics?.skills],["Source records",metrics?.sources]], [metrics]);
 return <main className="dashboard"><header className="dashHeader"><div className="dashBrand"><b>RSA</b><span>Knowledge Intelligence</span></div><div className="liveStatus"><i/>{status}</div></header>
  <section className="dashHero"><div><p>RSA SCC · LIVE KNOWLEDGE GRAPH</p><h1>Career knowledge,<br/><em>made visible.</em></h1><span>Explore coverage, maturity, pathways and evidence without opening Neo4j or writing Cypher.</span></div><aside><small>DATABASE STATUS</small><strong>{metrics?"Connected":"Checking"}</strong><span>{metrics?`${Number(metrics.streams||0).toLocaleString()} pathways available`:status}</span></aside></section>
  <section className="metricGrid">{cards.map(([label,value])=><article key={String(label)}><strong>{Number(value||0).toLocaleString()}</strong><span>{String(label)}</span></article>)}</section>
  <section className="questionSection"><div><p>LIVE DEMONSTRATION</p><h2>Questions worth asking</h2><span>Select any question to run it against the current graph.</span></div><div className="questionGrid">{queries.map((q,i)=><button key={q.id} className={active.id===q.id?"active":""} onClick={()=>run(q)} disabled={busy}><small>QUESTION {String(i+1).padStart(2,"0")}</small><b>{q.question}</b><span>Run live →</span></button>)}</div></section>
  <section className="dashWorkspace"><aside className="queryPanel"><div><p>QUERY LIBRARY</p><h2>Explore the graph</h2></div><form onSubmit={search}><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search a career or domain"/><button>Search</button></form><nav>{queries.map(q=><button key={q.id} className={active.id===q.id?"active":""} onClick={()=>run(q)}><b>{q.title}</b><span>{q.description}</span></button>)}</nav></aside>
   <section className="resultPanel"><header><div><p>LIVE NEO4J RESULT</p><h2>{active.title}</h2><span>{active.description}</span></div><b>{busy?"Working…":status}</b></header><div className="queryExplanation"><div><small>THE QUESTION</small><strong>{active.question}</strong></div><div><small>HOW THE GRAPH HANDLES IT</small><code>{active.handling}</code></div></div><div className="resultTable">{rows.length?<table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{columns.map(c=><td key={c}>{display(row[c])}</td>)}</tr>)}</tbody></table>:<div className="empty">{busy?"Querying the graph…":"No rows returned"}</div>}</div></section>
  </section><footer>RSA SCC Knowledge Graph <span>Read-only live demonstration</span></footer></main>;
}
function display(value:unknown){if(value===null||value===undefined||value==="")return"—";if(typeof value==="number")return value.toLocaleString();if(typeof value==="object")return JSON.stringify(value);return String(value);}
