import { NextRequest,NextResponse } from "next/server";
import { friendlyGraphError,runGraphQuery } from "../../../lib/neo4j";

const queries:Record<string,(term:string)=>{cypher:string;parameters?:Record<string,unknown>}>= {
  overview:()=>({cypher:`CALL { MATCH (n:Stream) RETURN count(n) AS streams } CALL { MATCH (n:CareerOutcome) RETURN count(n) AS careers } CALL { MATCH (n:Domain) RETURN count(n) AS domains } CALL { MATCH (n:EntranceExam) RETURN count(n) AS exams } CALL { MATCH (n:Skill) RETURN count(n) AS skills } CALL { MATCH (n:SourceRecord) RETURN count(n) AS sources } RETURN streams,careers,domains,exams,skills,sources`}),
  coverage:()=>({cypher:`MATCH (u:Universe) OPTIONAL MATCH (s:Stream)-[:BELONGS_TO_UNIVERSE]->(u) OPTIONAL MATCH (s)-[:LEADS_TO]->(c:CareerOutcome) RETURN u.name AS universe,u.version AS version,coalesce(u.ontology_definition_status,u.governance_status) AS ontology_status,coalesce(u.instance_data_status,u.governance_status) AS data_status,count(DISTINCT s) AS pathways,count(DISTINCT c) AS career_outcomes ORDER BY pathways DESC`}),
  domains:()=>({cypher:`MATCH (s:Stream)-[:CONTAINED_IN]->(d:Domain) OPTIONAL MATCH (s)-[:BELONGS_TO_UNIVERSE]->(u:Universe) OPTIONAL MATCH (s)-[:LEADS_TO]->(c:CareerOutcome) RETURN u.name AS universe,d.name AS domain,count(DISTINCT s) AS pathways,count(DISTINCT c) AS career_outcomes,coalesce(d.governance_status,'Not recorded') AS status ORDER BY pathways DESC LIMIT 25`}),
  governance:()=>({cypher:`MATCH (u:Universe) RETURN u.name AS universe,u.version AS version,coalesce(u.ontology_definition_status,u.governance_status) AS ontology_status,coalesce(u.instance_data_status,u.governance_status) AS data_status,u.source AS governing_source,u.last_refreshed AS last_refreshed ORDER BY universe`}),
  exams:()=>({cypher:`MATCH (e:EntranceExam) OPTIONAL MATCH (e)-[:BELONGS_TO_UNIVERSE]->(u:Universe) RETURN e.name AS exam,coalesce(u.name,'Cross-universe') AS universe,e.exam_level AS level,e.conducting_body AS conducting_body,e.governance_status AS status ORDER BY universe,exam LIMIT 40`}),
  provenance:()=>({cypher:`CALL { MATCH (src:SourceRecord) RETURN count(src) AS loaded_source_records } CALL { MATCH (n)-[r:SUPPORTED_BY_SOURCE]->(src:SourceRecord) RETURN count(r) AS evidence_links,count(DISTINCT n) AS traced_entities,count(DISTINCT src) AS linked_source_rows } RETURN loaded_source_records,evidence_links,traced_entities,linked_source_rows,CASE WHEN evidence_links=0 THEN 'Provenance links require attention' ELSE 'Traceability is active' END AS diagnosis`}),
  validation:()=>({cypher:`CALL { MATCH (s:Stream) WHERE NOT EXISTS { MATCH (s)-[:CONTAINED_IN]->(:Domain) } RETURN count(s) AS streams_without_domain } CALL { MATCH (s:Stream) WHERE NOT EXISTS { MATCH (s)-[:LEADS_TO]->(:CareerOutcome) } RETURN count(s) AS streams_without_outcome } CALL { MATCH (c:CareerOutcome) WHERE NOT EXISTS { MATCH (:Stream)-[:LEADS_TO]->(c) } RETURN count(c) AS dangling_outcomes } RETURN streams_without_domain,streams_without_outcome,dangling_outcomes,CASE WHEN streams_without_domain+streams_without_outcome+dangling_outcomes=0 THEN 'PASS' ELSE 'ACTION NEEDED' END AS verdict`}),
  engineering:()=>({cypher:`MATCH (s:Stream)-[:LEADS_TO]->(c:CareerOutcome) OPTIONAL MATCH (s)-[:CONTAINED_IN]->(d:Domain) OPTIONAL MATCH (s)-[:BELONGS_TO_UNIVERSE]->(u:Universe) WHERE toLower(coalesce(d.name,'')) CONTAINS 'engineering' OR toLower(coalesce(s.name,'')) CONTAINS 'engineering' RETURN c.name AS career,s.name AS pathway,d.name AS domain,u.name AS universe,coalesce(c.governance_status,s.governance_status) AS status ORDER BY career LIMIT 30`}),
  search:(term)=>({parameters:{term},cypher:`MATCH (s:Stream)-[:LEADS_TO]->(c:CareerOutcome) OPTIONAL MATCH (s)-[:CONTAINED_IN]->(d:Domain) OPTIONAL MATCH (s)-[:BELONGS_TO_UNIVERSE]->(u:Universe) WHERE toLower(coalesce(c.name,'')) CONTAINS toLower($term) OR toLower(coalesce(s.name,'')) CONTAINS toLower($term) OR toLower(coalesce(d.name,'')) CONTAINS toLower($term) RETURN c.name AS career,s.name AS pathway,d.name AS domain,u.name AS universe,coalesce(c.governance_status,s.governance_status) AS status ORDER BY career LIMIT 40`}),
};

export async function POST(request:NextRequest){try{const body=await request.json() as{id?:string;term?:string};const id=String(body.id||"");if(!queries[id])return NextResponse.json({error:"Unknown dashboard query."},{status:400});const result=await runGraphQuery(queries[id](String(body.term||"")).cypher,queries[id](String(body.term||"")).parameters||{});return NextResponse.json(result);}catch(error){return NextResponse.json({error:friendlyGraphError(error)},{status:500});}}
